### PR TITLE
feat: Add a way to filter our some paths

### PR DESCRIPTION
**Pull request by ltouati**
When using the rocket file server, a lot of transactions are sent to sentry. Adds a configuration parameter to filter a series of paths

### CODE REVIEW

**Comment by Hugo-C** [comment]
I am also interrested in this feature !
I'll take a look at the PR.
Did you see/try [trace_sampler](https://docs.sentry.io/platforms/rust/performance/#configure) ? It could be a viable option that is more flexible but I didn't find an example on how to use it yet.

**Comment by intgr** [comment]
Sentry documentation describes a `traces_sampler` callback function which can make decisions about which transactions get sampled and at what rate.

https://docs.sentry.io/platforms/rust/configuration/sampling/

The documentation says it's not supported by Rust yet, but looks like a few relevant pull requests have actually been merged, maybe the documentation is just outdated.

* https://github.com/getsentry/sentry-rust/pull/510
* https://github.com/getsentry/sentry-rust/pull/512

That seems like a more flexible approach. And if Sentry SDK already provides similar functionality, it's best not to duplicate it.

**Comment by intgr** [comment]
Ah sorry, Hugo-C already mentioned `traces_sampler`. I hadn't read his comment yet :)

**Comment by Hugo-C** [comment]
The `traces_sampler` does work (tested [here](https://github.com/Hugo-C/rocket-sentry/commit/aa43a9a483d020b235cb1a9b23329f0ee70f254f)). Ideally we have to find a way for users to set it on fairing initialisation, maybe something like [Rocket's Shield](https://api.rocket.rs/v0.5/src/rocket/shield/shield.rs#100-189) ? So some big changes on how `RocketSentry` have to be initialized 😅
The big plus of `traces_sampler` is that indeed it allows to set a lower rate instead of completely filter it out.

**Comment by Hugo-C** [comment]
If no one plans to work on this ticket, I'll give it a go next week

**Comment by intgr** [comment]
@Hugo-C has contributed a PR for `traces_sampler` integration #74, which is a more flexible mechanism that also solves this use case. I will go ahead and close this one.

* #74

**Pull request closed without merging**
